name: boomerang
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  google_fonts: ^3.0.1

  http: ^0.13.5

  convert: ^3.1.1

  intl: ^0.17.0

  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons:


flutter:
  uses-material-design: true

  assets:
    - asset/img/
flutter_icons:
  android: true
  ios: true
  image_path: "asset/icon.png"